#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.


In [27]:

import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [28]:
print("Type of list_ Variable : ",type(list_))
print("Type of array_list Variable : ",type(array_list))
print("Data Type of elements in array_list Variable : ",array_list.dtype)

Type of list_ Variable :  <class 'list'>
Type of array_list Variable :  <class 'numpy.ndarray'>
Data Type of elements in array_list Variable :  <U1


In [29]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [30]:
for i in list_:
    print(f"Type of list_ {i} Variable : {type(i)}")
    
for j in array_list:
    print(f"Type of array_list {j} Variable : {type(j)}")

Type of list_ 1 Variable : <class 'str'>
Type of list_ 2 Variable : <class 'str'>
Type of list_ 3 Variable : <class 'str'>
Type of list_ 4 Variable : <class 'str'>
Type of list_ 5 Variable : <class 'str'>
Type of array_list 1 Variable : <class 'numpy.str_'>
Type of array_list 2 Variable : <class 'numpy.str_'>
Type of array_list 3 Variable : <class 'numpy.str_'>
Type of array_list 4 Variable : <class 'numpy.str_'>
Type of array_list 5 Variable : <class 'numpy.str_'>


#Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)



In [31]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
array_list = np.array(object=list_,dtype=int)

In [32]:
for i in list_:
    print(f"Type of list_ {i} Variable : {type(i)}")
    
for j in array_list:
    print(f"Type of array_list {j} Variable : {type(j)}")

Type of list_ 1 Variable : <class 'str'>
Type of list_ 2 Variable : <class 'str'>
Type of list_ 3 Variable : <class 'str'>
Type of list_ 4 Variable : <class 'str'>
Type of list_ 5 Variable : <class 'str'>
Type of array_list 1 Variable : <class 'numpy.int64'>
Type of array_list 2 Variable : <class 'numpy.int64'>
Type of array_list 3 Variable : <class 'numpy.int64'>
Type of array_list 4 Variable : <class 'numpy.int64'>
Type of array_list 5 Variable : <class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [33]:

num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
num_array.shape


(2, 3)

In [35]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [36]:
arr = np.zeros((3,3))

In [37]:

arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:

arr.size

9

In [39]:
arr.shape

(3, 3)

In [40]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [41]:

arr1 = np.eye(5)

In [42]:

arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
arr1.shape

(5, 5)

In [44]:
arr1.size

25